#!/usr/bin/env python3
"""Cut the self-hosted woff2 subsets in public/assets/fonts/ from upstream sources.

Every woff2 in public/assets/fonts/ is generated by this script — nothing in
that directory is hand-made or taken verbatim from a CDN anymore. The subsets
are Google Fonts' latin / latin-ext unicode ranges (copied verbatim, so
subsetting behaviour matches what the old @import used to fetch), plus the
arrow codepoints U+2190-2193 in the Geist faces: the site's copy uses "->" and
"<-" (U+2192 / U+2190) in proof figures, card links and prose links, and
Google's latin range skips them while including U+2191 / U+2193. Newsreader
gets no arrow additions because the upstream typeface simply has no arrow
glyphs; serif-context arrows are carried by geist-arrows.woff2, a four-glyph
cut of Geist that sits second in the --serif stack (see the @font-face notes
in public/assets/style.css).

Also NOT coverable from these faces, verified against the upstream cmaps:
U+03BA kappa and the theme-toggle's U+2600 / U+263D sun and moon exist in none
of the three upstreams, so they intentionally stay on the --symbol-tail /
system fallback.

Fetching the sources (into any scratch directory):

    npm pack geist@1.7.2 --pack-destination <dir>
    tar -xzf <dir>/geist-1.7.2.tgz -C <dir>          # unpacks to <dir>/package
    curl -sL -o <dir>/Newsreader.ttf        "https://raw.githubusercontent.com/google/fonts/main/ofl/newsreader/Newsreader%5Bopsz,wght%5D.ttf"
    curl -sL -o <dir>/Newsreader-Italic.ttf "https://raw.githubusercontent.com/google/fonts/main/ofl/newsreader/Newsreader-Italic%5Bopsz,wght%5D.ttf"

Then, from the repo root:

    uv run --with "fonttools[woff]" python scripts/subset-fonts.py <dir>

The script asserts the source font VERSIONS below before cutting, so a moved
google/fonts main or a bumped npm tag fails loudly instead of silently
shipping different glyphs. If an upstream legitimately moves, update the
expected version here, re-run, and eyeball a before/after screenshot diff --
then keep the unicode-range declarations in public/assets/style.css and
public/resume.html in sync with what this prints.

Newsreader upstream carries an optical-size axis (opsz 6-72) alongside weight;
this script pins opsz at its fvar default (18) and keeps only the weight axis,
reproducing the "wght instance" files the site originally took from
@fontsource-variable/newsreader -- the opsz-bearing files are ~2.3x the bytes
for an axis the site never varies. The Geist sources are already wght-only.
"""

import sys
from io import BytesIO
from pathlib import Path

from fontTools import subset
from fontTools.ttLib import TTFont
from fontTools.varLib import instancer

REPO = Path(__file__).resolve().parent.parent
OUT_DIR = REPO / "public" / "assets" / "fonts"

# Google Fonts' own latin / latin-ext ranges, verbatim. These are the ranges
# declared in public/assets/style.css -- if you change one here, change it
# there (and in public/resume.html, which repeats the Geist declarations).
LATIN = (
    "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, "
    "U+0304, U+0308, U+0329, U+2000-206F, U+20AC, U+2122, U+2191, U+2193, "
    "U+2212, U+2215, U+FEFF, U+FFFD"
)
LATIN_EXT = (
    "U+0100-02BA, U+02BD-02C5, U+02C7-02CC, U+02CE-02D7, U+02DD-02FF, "
    "U+0304, U+0308, U+0329, U+1D00-1DBF, U+1E00-1E9F, U+1EF2-1EFF, U+2020, "
    "U+20A0-20AB, U+20AD-20C0, U+2113, U+2C60-2C7F, U+A720-A7FF"
)
ARROWS = "U+2190-2193"  # <- ^ -> v; Google's latin range has only ^ and v

# nameID 5 of each source, asserted before cutting.
EXPECT_VERSION = {
    "Geist": "Version 1.800",
    "Geist Mono": "Version 1.700",
    "Newsreader": "Version 1.003",
    "Newsreader Italic": "Version 1.003",
}


def parse_ranges(*specs: str) -> set[int]:
    cps: set[int] = set()
    for spec in specs:
        for tok in spec.split(","):
            tok = tok.strip().removeprefix("U+")
            if "-" in tok:
                a, b = tok.split("-")
                cps.update(range(int(a, 16), int(b, 16) + 1))
            else:
                cps.add(int(tok, 16))
    return cps


def version_of(font: TTFont) -> str:
    return next(r.toUnicode() for r in font["name"].names if r.nameID == 5)


def features(font: TTFont) -> set[str]:
    tags: set[str] = set()
    for table in ("GSUB", "GPOS"):
        if table in font and font[table].table.FeatureList:
            tags |= {r.FeatureTag for r in font[table].table.FeatureList.FeatureRecord}
    return tags


def cut(font: TTFont, cps: set[int], out_name: str, must_have: set[int] = frozenset()) -> None:
    # Re-parse from a pickled copy so repeated cuts of one source stay independent.
    buf = BytesIO()
    font.save(buf)
    buf.seek(0)
    work = TTFont(buf)

    options = subset.Options()
    # Keep every OpenType feature and name record the source ships: the ONLY
    # thing this script narrows is the codepoint set. A curated feature list is
    # a false economy -- fontTools' default silently drops `tnum`, and this site
    # sets `font-variant-numeric: tabular-nums` in sixteen places, so the figures
    # in every metric, folio and proof row would quietly stop aligning.
    options.layout_features = ["*"]
    options.name_IDs = ["*"]
    subsetter = subset.Subsetter(options=options)
    subsetter.populate(unicodes=sorted(cps))
    subsetter.subset(work)

    kept = set(work.getBestCmap().keys())
    missing = must_have - kept
    if missing:
        raise SystemExit(f"{out_name}: required codepoints missing from source: "
                         + ", ".join(f"U+{c:04X}" for c in sorted(missing)))

    # The tabular-figures guard, asserted rather than assumed. Only meaningful
    # for a cut that actually carries digits -- the latin-ext range has none, so
    # its numeric features prune to nothing legitimately.
    src_tags, out_tags = features(font), features(work)
    if set(range(0x30, 0x3A)) <= kept:
        for tag in ("tnum", "pnum"):
            if tag in src_tags and tag not in out_tags:
                raise SystemExit(f"{out_name}: source has '{tag}' but the cut lost it; "
                                 "font-variant-numeric would silently stop working")

    work.flavor = "woff2"
    out = OUT_DIR / out_name
    work.save(str(out))
    print(f"  {out_name}: {len(kept)} codepoints, {len(out_tags)} features, "
          f"{out.stat().st_size:,} bytes")


def load(path: Path, family: str) -> TTFont:
    font = TTFont(str(path))
    ver = version_of(font)
    if ver != EXPECT_VERSION[family]:
        raise SystemExit(f"{path.name}: expected {family} '{EXPECT_VERSION[family]}', "
                         f"got '{ver}' -- upstream moved; see the docstring")
    return font


def main() -> None:
    if len(sys.argv) != 2:
        raise SystemExit(__doc__)
    src = Path(sys.argv[1])

    latin = parse_ranges(LATIN)
    latin_arrows = parse_ranges(LATIN, ARROWS)
    latin_ext = parse_ranges(LATIN_EXT)
    arrows = parse_ranges(ARROWS)
    used_arrows = {0x2190, 0x2192}  # the two the copy actually uses today

    print("Geist (sans):")
    geist = load(src / "package/dist/fonts/geist-sans/Geist-Variable.ttf", "Geist")
    cut(geist, latin_arrows, "geist-latin.woff2", must_have=used_arrows)
    cut(geist, latin_ext, "geist-latin-ext.woff2")
    cut(geist, arrows, "geist-arrows.woff2", must_have=used_arrows)
    geist.close()

    print("Geist Mono:")
    mono = load(src / "package/dist/fonts/geist-mono/GeistMono-Variable.ttf", "Geist Mono")
    cut(mono, latin_arrows, "geist-mono-latin.woff2", must_have=used_arrows)
    cut(mono, latin_ext, "geist-mono-latin-ext.woff2")
    mono.close()

    for family, ttf, stem in (
        ("Newsreader", "Newsreader.ttf", "newsreader-latin"),
        ("Newsreader Italic", "Newsreader-Italic.ttf", "newsreader-latin-italic"),
    ):
        print(f"{family}:")
        news = load(src / ttf, family)
        opsz = next(a for a in news["fvar"].axes if a.axisTag == "opsz")
        if opsz.defaultValue != 18.0:
            raise SystemExit(f"{ttf}: opsz default moved from 18 to {opsz.defaultValue}; "
                             "the pinned instance would no longer match the shipped files")
        instancer.instantiateVariableFont(news, {"opsz": opsz.defaultValue},
                                          inplace=True, updateFontNames=False)
        ext_stem = stem.replace("-latin", "-latin-ext")
        cut(news, latin, f"{stem}.woff2")
        cut(news, latin_ext, f"{ext_stem}.woff2")
        news.close()

    print("\nDeclared unicode-range must be (style.css AND resume.html for Geist):")
    print("  latin (Geist, Geist Mono):  " + LATIN.replace("U+2191, U+2193", "U+2190-2193"))
    print("  latin (Newsreader):         " + LATIN)
    print("  latin-ext (all):            " + LATIN_EXT)
    print("  geist-arrows.woff2:         " + ARROWS)


if __name__ == "__main__":
    main()
